# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uAGkTSv2lzKeWGbquDgCb-51lj9EOkfO
"""

# 上辺
upper_base=10
# 下辺
low_base=20
# 高さ
height=5

# 台形の面積を計算
trapezoid_area=(upper_base+low_base)*height/2
# 結果と出力
print(f"台形の面積は{trapezoid_area}㎠です")