# -*- coding: utf-8 -*-
"""calculator2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LkuFuEPvnshsRf6ALFxWFgwoswktMBt6
"""

import csv

num_1 = int(input('Enter your first number:'))
num_2 = int(input('Enter your second number:'))

# 計算結果のリストを作成
results = [
    ["Operation", "Result"],
    ["{} + {}".format(num_1, num_2), num_1 + num_2],
    ["{} - {}".format(num_1, num_2), num_1 - num_2],
    ["{} * {}".format(num_1, num_2), num_1 * num_2],
    ["{} / {}".format(num_1, num_2), num_1 / num_2]
]

# CSVファイルにデータを書き込む
csv_file_path = "calculation_results.csv"
with open(csv_file_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(results)

print(f"計算結果が {csv_file_path} に書き込まれました。")