# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fC-DMfdz5hJK6nGoIpCqRab6PtBRYWxv
"""

num_1 = int(input('Enter your first number:'))
num_2 = int(input('Enter your second number:'))

# 足し算
print('{} + {} = '.format(num_1,num_2))
print(num_1+num_2)

# 引き算
print('{} - {} = '.format(num_1,num_2))
print( num_1-num_2)

# 掛け算
print('{} * {} = '.format(num_1,num_2))
print(num_1*num_2)

#割り算
print('{} / {} = '.format(num_1,num_2))
print(num_1/num_2)