# -*- coding: utf-8 -*-
"""calculator4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VmlodQZV18kNL1WyK0-IOwoP6nGR0ig8
"""

import tkinter as tk

def button_click(value):
    current = entry_var.get()
    entry_var.set(current + str(value))

def clear_entry():
    entry_var.set("")

def calculate():
    try:
        result = eval(entry_var.get())
        entry_var.set(result)
    except Exception as e:
        entry_var.set("Error")

# メインウィンドウの作成
root = tk.Tk()
root.title("電卓")

# エントリウィジェットの作成
entry_var = tk.StringVar()
entry = tk.Entry(root, textvariable=entry_var, font=('Arial', 16), justify='right')
entry.grid(row=0, column=0, columnspan=4, padx=10, pady=10)

# ボタンのレイアウト
buttons = [
    '7', '8', '9', '/',
    '4', '5', '6', '*',
    '1', '2', '3', '-',
    '0', '.', '=', '+'
]

row_val = 1
col_val = 0

for button in buttons:
    tk.Button(root, text=button, padx=20, pady=20, font=('Arial', 16),
              command=lambda b=button: button_click(b) if b != '=' else calculate()).grid(row=row_val, column=col_val)
    col_val += 1
    if col_val > 3:
        col_val = 0
        row_val += 1

# クリアボタン
tk.Button(root, text='C', padx=20, pady=20, font=('Arial', 16), command=clear_entry).grid(row=row_val, column=col_val)

# メインループの開始
root.mainloop()