# -*- coding: utf-8 -*-
"""calculator4A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UsR1OfLYT5V1Py5iiRHZ4U0ZPl3JElRc
"""

import tkinter as tk

def calculate():
    try:
        num_1 = int(entry_num1.get())
        num_2 = int(entry_num2.get())

        # Calculate results
        result_var.set("Results:\n")
        result_var.set(result_var.get() + "{} + {} = {}\n".format(num_1, num_2, num_1 + num_2))
        result_var.set(result_var.get() + "{} - {} = {}\n".format(num_1, num_2, num_1 - num_2))
        result_var.set(result_var.get() + "{} * {} = {}\n".format(num_1, num_2, num_1 * num_2))
        result_var.set(result_var.get() + "{} / {} = {:.2f}\n".format(num_1, num_2, num_1 / num_2))

    except ValueError:
        result_var.set("Error: Please enter valid numbers.")

# Create the main window
root = tk.Tk()
root.title("Calculator")

# Create and pack entry widgets
entry_num1 = tk.Entry(root, width=10)
entry_num1.grid(row=0, column=0, padx=5, pady=5)

entry_num2 = tk.Entry(root, width=10)
entry_num2.grid(row=0, column=1, padx=5, pady=5)

# Create and pack the calculate button
calculate_button = tk.Button(root, text="Calculate", command=calculate)
calculate_button.grid(row=1, column=0, columnspan=2, pady=10)

# Create and pack the result label
result_var = tk.StringVar()
result_label = tk.Label(root, textvariable=result_var, justify='left')
result_label.grid(row=2, column=0, columnspan=2, padx=5, pady=5)

# Start the main event loop
root.mainloop()